// Word lists for the game
const WORDS_4 = [
  'ABLE', 'ACID', 'AGED', 'ALSO', 'AREA', 'ARMY', 'AWAY', 'BACK', 'BALL', 'BAND',
  'BANK', 'BASE', 'BATH', 'BEAR', 'BEAT', 'BEEF', 'BEEN', 'BEER', 'BELL', 'BELT',
  'BEST', 'BILL', 'BIRD', 'BLOW', 'BLUE', 'BOAT', 'BODY', 'BOMB', 'BOND', 'BONE',
  'BOOK', 'BOOM', 'BOOT', 'BORN', 'BOSS', 'BOTH', 'BOWL', 'BULK', 'BURN', 'BUSH',
  'BUSY', 'CALL', 'CALM', 'CAME', 'CAMP', 'CARD', 'CARE', 'CASE', 'CASH', 'CAST',
  'CELL', 'CHAT', 'CHIP', 'CITY', 'CLUB', 'COAL', 'COAT', 'CODE', 'COLD', 'COME',
  'COOK', 'COOL', 'COPY', 'CORE', 'COST', 'CREW', 'CROP', 'DARK', 'DATA', 'DATE',
  'DEAL', 'DEBT', 'DEEP', 'DEER', 'DESK', 'DIAL', 'DIET', 'DISK', 'DIVE', 'DOCK',
  'DOES', 'DOOR', 'DOSE', 'DOWN', 'DRAW', 'DROP', 'DRUG', 'DRUM', 'DUAL', 'DUCK',
  'DUST', 'DUTY', 'EARN', 'EASE', 'EAST', 'EDGE', 'EDIT', 'EGGY', 'ELAN', 'EMIT'
];

const WORDS_5 = [
  'APPLE', 'BREAD', 'CHAIR', 'DANCE', 'EAGLE', 'FRAME', 'GRACE', 'HOUSE', 'IDEAL', 'JOKER',
  'KNOCK', 'LEMON', 'MANGO', 'NIGHT', 'OCEAN', 'PAINT', 'QUIET', 'RIVER', 'SWEET', 'TIGER',
  'UNDER', 'VIVID', 'WHALE', 'XEROX', 'YIELD', 'ZEBRA', 'BLAZE', 'CRISP', 'DREAM', 'EARTH',
  'FLUTE', 'GHOST', 'HAPPY', 'IVORY', 'JELLY', 'KNIFE', 'LIGHT', 'MAGIC', 'NOVEL', 'ORBIT',
  'PLANT', 'QUEEN', 'RODEO', 'SMILE', 'TRACK', 'UNITY', 'VOICE', 'WIRED', 'XYLEN', 'YOUTH',
  'ANGLE', 'BRUSH', 'COVER', 'DRINK', 'EXTRA', 'FLASH', 'GIANT', 'HILLO', 'INPUT', 'JOINT',
  'KNOCK', 'LATCH', 'MIRTH', 'NUDGE', 'OPINE', 'PRIME', 'QUEST', 'ROOST', 'STOMP', 'THROB',
  'UNZIP', 'VERGE', 'WRECK', 'XTEND', 'ZESTY', 'AISLE', 'BLUSH', 'CREAK', 'DRAFT', 'ERUPT',
  'FUNKY', 'GLOVE', 'HOUND', 'INLET', 'JUMPY', 'KARMA', 'LAUGH', 'MOTTO', 'NURSE', 'OLIVE',
  'PRAWN', 'QUIRK', 'REGAL', 'SWORD', 'TOWEL', 'URBAN', 'VAULT', 'WITTY', 'YUMMY', 'ZONED'
];

const WORDS_6 = [
  'ANIMAL', 'BRIGHT', 'CIRCLE', 'DANGER', 'FLIGHT', 'GROWTH', 'HAMMER', 'IGNORE', 'JUNGLE', 'KITTEN',
  'LADDER', 'MAGNET', 'NATURE', 'ORANGE', 'PACKET', 'QUENCH', 'ROCKET', 'SUMMIT', 'TALENT', 'UNIQUE',
  'VISION', 'WONDER', 'YELLOW', 'BOTHER', 'CREATE', 'DOUBLE', 'EFFORT', 'FABRIC', 'GADGET', 'HUNTER',
  'IMPACT', 'JUMBLE', 'KINDLY', 'LOCKET', 'MODERN', 'NUMBER', 'ONLINE', 'PEOPLE', 'QUIVER', 'REMARK',
  'SENDER', 'TARGET', 'UPHILL', 'VELVET', 'WRENCH', 'XYLOID', 'YEARLY', 'ZEPHYR', 'BACKUP', 'CANYON',
  'DESIGN', 'EASIER', 'FRIEND', 'GROWTH', 'HEIGHT', 'INCOME', 'JIGSAW', 'KNEELS', 'LAPTOP', 'MARKET',
  'NATION', 'OPTION', 'PARADE', 'QUARTZ', 'RESULT', 'SILENT', 'THIRST', 'UPDATE', 'VISUAL', 'WINTER',
  'ACCENT', 'BELIEF', 'CUSTOM', 'DIVIDE', 'EXPORT', 'FORGED', 'GALAXY', 'HEIGHT', 'INSECT', 'JACKET',
  'KIDNEY', 'LINGER', 'MENTOR', 'NOTICE', 'OFFICE', 'PARENT', 'REWIND', 'SUFFIX', 'TUNNEL', 'UNFOLD',
  'VACANT', 'WANDER', 'XENIAL', 'YONDER', 'ZIPPER', 'ACCORD', 'BREEZE', 'CIRCLE', 'DARING', 'ELAPSE'
];

const WORDS_7 = [
  'ADVANCE', 'AGAINST', 'ABANDON', 'BALANCE', 'CAPTURE', 'DIGITAL', 'ELASTIC', 'FANTASY',
  'FREEDOM', 'GATEWAY', 'HARVEST', 'JOURNEY', 'JUSTICE', 'KINSMAN', 'LANTERN', 'MONSTER',
  'NETWORK', 'OPTIONS', 'PASSAGE', 'QUALITY', 'RECLAIM', 'REQUEST', 'RESPECT', 'SAMPLED',
  'TEACHER', 'UNCOVER', 'VENTURE', 'WAITING', 'WEALTHY', 'ZEALOTS', 'ANALYST', 'BENEFIT',
  'CARTOON', 'DANGERS', 'EVENING', 'FICTION', 'GRAMMAR', 'HOLDING', 'IMAGINE', 'JOURNAL',
  'KINGDOM', 'LETTERS', 'MESSAGE', 'NATURAL', 'OUTSIDE', 'PACKAGE', 'QUICKER', 'RADIANT',
  'SETTING', 'TROUBLE', 'UPGRADE', 'VICTORY', 'WARNING', 'WRITERS', 'ALGEBRA', 'BUFFERS',
  'CYCLONE', 'DEFENSE', 'ECOLOGY', 'FAILURE', 'GLIMPSE', 'HOSTILE', 'INJURED', 'JUSTICE',
  'KNITTED', 'LOGICAL', 'MANAGER', 'NOMINEE', 'OPERATE', 'PREDICT', 'QUARTER', 'REJOICE',
  'SINCERE', 'THEATER', 'UNKNOWN', 'VENTURE', 'WAITING', 'XYLITOL', 'YAWNING', 'ZENITHS',
  'BREATHE', 'CAPTURE', 'DELIVER', 'EXCITED', 'FANTASY', 'GLITTER', 'HARVEST', 'INSECTS',
  'JUSTICE', 'KINGDOM', 'LETTERS', 'MAGNETS', 'NOURISH', 'OPINION', 'PACKAGE', 'QUALITY',
  'REFINED', 'STRETCH', 'TRIUMPH', 'UPGRADE'
];

const WORDS_8 = [
  'ABSOLUTE', 'BEHAVIOR', 'CAMPSITE', 'DAUGHTER', 'ELECTION', 'FOREHEAD', 'GRATEFUL', 'HANDBALL',
  'IDENTITY', 'JUDGMENT', 'KEYBOARD', 'LIFELINE', 'MEDICINE', 'NOTATION', 'OVERCOME', 'PARADISE',
  'QUANTITY', 'RESOURCE', 'SCENARIO', 'TEMPLATE', 'ULTIMATE', 'VACATION', 'WILDLIFE', 'YARDSTICK',
  'BACKFIRE', 'BUILDING', 'CONTRACT', 'DECISION', 'ELEVATOR', 'FEEDBACK', 'GENEROUS', 'HOSPITAL',
  'INSTANCE', 'JOURNALY', 'KNEELING', 'LEARNING', 'MEDICINE', 'NATIONAL', 'OPERATOR', 'PATHWAYS',
  'QUESTION', 'RADIATOR', 'SCENARIO', 'TRACKING', 'UMBRELLA', 'VACATION', 'WALLPAPER', 'YARDWORK',
  'ZEBRASIC', 'APPLAUSE', 'BACKHAND', 'CREATION', 'DAUGHTER', 'ELEPHANT', 'FUNCTION', 'GEOMETRY',
  'HEADLINE', 'INTERNET', 'JEALOUSY', 'KICKBALL', 'LANDLORD', 'MANIFEST', 'NEGATIVE', 'OUTREACH',
  'PARTICLE', 'QUANTITY', 'RELATION', 'SHOULDER', 'TRIANGLE', 'UPRIGHTLY', 'VELOCITY', 'WISHLIST',
  'YARDLINE', 'ZOOKEEPER', 'BACKBONE', 'BIRTHDAY', 'CHARCOAL', 'DOWNLOAD', 'EXERCISE', 'FILENAME',
  'GULLIBLE', 'HANDSHAKE', 'IDENTIFY', 'JEWELRYS', 'KILLJOYS', 'LANGUAGE', 'MOBILITY', 'NECKLACE',
  'OPERATOR', 'PIPELINE', 'QUANTITY', 'RAILROAD', 'SCHEDULE', 'TRANSFER', 'ULTIMATE', 'VACATION',
  'WORKFORCE', 'YARDSTICK', 'ZEALOTRY', 'BACKWARD'
];

const WORDS_9 = [
  'ADVENTURE', 'BACKWARDS', 'BEAUTIFUL', 'CHALLENGE', 'DANGEROUS', 'EDUCATION', 'FORGOTTEN', 'GRATEFUL',
  'HEADLIGHT', 'IMPORTANT', 'JEALOUSIES', 'KEYBOARDED', 'LANDSCAPE', 'MARKETING', 'NATURALLY', 'OBJECTIVE',
  'PAPERWORK', 'QUICKSTEP', 'REBELLION', 'SATELLITE', 'TELEPHONE', 'UNDERWEAR', 'VALUATION', 'WALLPAPER',
  'YOUTHFULS', 'ZINCIFIED', 'ATTENTION', 'BACKPACKS', 'CELEBRATE', 'DANGEROUS', 'ELSEWHERE', 'FORMATION',
  'GRAPHICAL', 'HEARTBEAT', 'INJECTION', 'JUNCTIONS', 'KNOCKDOWN', 'LANDOWNER', 'LIFESAVER', 'MATERNITY',
  'NIGHTFALL', 'ORGANIZER', 'PACKHORSE', 'QUICKNESS', 'ROADBLOCK', 'SIDEBURNS', 'TEMPLATEZ', 'ULTERIORLY',
  'VACATIONZ', 'WATERFALL', 'ADVENTURE', 'BOOKMARKZ', 'CLEARINGS', 'DETECTORS', 'ELEVATORZ', 'FIREPROOF',
  'GREENROOM', 'HANDSTAND', 'IDENTICAL', 'JUDGMENTZ', 'KNOWLEDGE', 'LEAFLETSZ', 'MACHINERY', 'NEWSSTAND',
  'OPERATIVE', 'PIONEERED', 'QUALIFIED', 'REVIEWERZ', 'SNAPSHOTZ', 'TOLERANCE', 'UNDERFOOT', 'VIGILANTE',
  'WAVELENGTH', 'YEARBOOKS', 'ZOOLOGIST', 'ARTILLERY', 'BLUEPRINT', 'CAREGIVER', 'DANGEROUS', 'EMBEZZLER',
  'FOOTSTEPS', 'GUARDIANZ', 'HIGHPOINT', 'INSURANCE', 'JOURNALIST', 'KICKSTAND', 'LIGHTBULB', 'MARATHONS',
  'NIGHTLIFE', 'OUTREACHZ', 'PRIVATELY', 'QUICKFIRE', 'ROUGHNESS', 'SEAMASTER', 'TAKEOVERS', 'UNIVERSAL',
  'VOCALISTS', 'WANDERERS', 'XEROGRAPH', 'YEARLINGS'
];

const WORDS_10 = [
  'ABUNDANCE', 'BACKSTROKE', 'CALCULATOR', 'DANGEROUS', 'EARTHQUAKE', 'FABRICATED', 'GENERATION', 'HELICOPTER',
  'IMPRESSIVE', 'JOURNALIST', 'KANGAROOS', 'LEADERSHIP', 'MOTIVATION', 'NEGOTIABLE', 'OBLITERATE', 'POLITICIAN',
  'QUARANTINE', 'RESTAURANT', 'STOPWATCH', 'TELEVISION', 'UNDERTAKER', 'VOLATILITY', 'WANDERLUST', 'XENOPHOBIA',
  'YOUTHFULLY', 'ZOOLOGISTS', 'ABSORPTION', 'BRAINSTORM', 'CELEBRATION', 'DETRACTORS', 'EXHIBITION', 'FRUSTRATED',
  'GOVERNMENT', 'HOUSEPLANT', 'IMPRESSION', 'JUDGEMENTAL', 'KNOWLEDGEY', 'LUXURIOUSLY', 'MAGISTRATE', 'NAVIGATION',
  'OVERCHARGE', 'PRODUCTION', 'QUICKENING', 'RESOLUTION', 'SPACESHIPS', 'TERMINATED', 'UNBREAKABLE', 'VINDICATED',
  'WORKAHOLIC', 'EXCURSIONS', 'BENEFICIAL', 'CROSSWORDS', 'DREAMSCAPE', 'ENCLOSURES', 'FREELANCED', 'GRACIOUSLY',
  'HOMECOMING', 'INFLEXIBLE', 'JUNKDRAWER', 'KEYSTROKES', 'LENGTHIEST', 'MASTERMIND', 'NEWSWORTHY', 'OPPOSITION',
  'PERFECTION', 'QUICKSTART', 'REHEARSING', 'STRUCTURED', 'TECHNOLOGY', 'UNPLUGGING', 'VICTORIOUS', 'WORKAROUND',
  'ATTACHMENTS', 'BLUEPRINTS', 'COMMANDERS', 'DISTURBING', 'EARTHBOUND', 'FORECASTER', 'GENEROSITY', 'HEADPHONES',
  'IGNORANTLY', 'JOYFULNESS', 'KNIGHTHOOD', 'LANDOWNERS', 'MOONLIGHTS', 'NIGHTSTAND', 'OBJECTIVES', 'PERSISTENCE',
  'QUICKSANDS', 'RHETORICAL', 'SUPERPOWER', 'TRANSCENDS', 'UNANSWERED', 'VALIDATING', 'WANDERINGS', 'YEARLONGER',
  'ZOOMORPHIC', 'ARBITRATOR', 'BIOGRAPHER', 'COPYWRITER'
];

const WORDS_11 = [
  'ABOMINATION', 'ABERRATIONS', 'ABHORRENTLY', 'ABNEGATIONS', 'ABUNDANCIES', 'ACCELERATED', 'ACCEPTANCES',
  'ACCLIMATIZE', 'ACCOMPANIED', 'ACCOMPLICES', 'ACCUSATIONS', 'ADJUDICATED', 'ADMIRATION', 'ADVENTURING',
  'ADVERTISERS', 'AFFIRMATIVE', 'AGGREGATION', 'AGGRAVATION', 'AGRICULTURE', 'ALARMEDNESS', 'ALIENATIONS',
  'ALLEGATIONS', 'ALLITERATION', 'ALTERCATION', 'AMBIGUITIES', 'AMBITIOUSLY', 'AMPLIFICATION', 'ANNIHILATES',
  'ANTAGONISTS', 'APPRECIATION', 'APPEARANCES', 'APPLICATION', 'APPOINTMENTS', 'APPRENTICES', 'ARBITRATORS',
  'ARTICULATES', 'ASPIRATION', 'ASSIGNMENTS', 'ASSOCIATIONS', 'ATMOSPHERES', 'ATTENUATION', 'ATTRACTIONS',
  'AUTHORITIES', 'AUTHORIZERS', 'AWKWARDNESS', 'BACKGROUNDS', 'BENEFICIARY', 'BENEFACTORS', 'BIOGRAPHERS',
  'BRIGHTENING', 'BRUTALITIES', 'CALCULATORS', 'CELEBRATIONS', 'CELLULITIES', 'CHALLENGING', 'CHANGEOVERS',
  'CHARACTERS', 'CITIZENSHIP', 'CLASSIFYING', 'COEXISTENCE', 'COLLABORATION', 'COLLECTIBLES', 'COMFORTABLE',
  'COMMUNICATE', 'COMPARISON', 'COMPETITIONS', 'COMPLACENCY', 'COMPLEXITY', 'COMPLIMENTS', 'CONCEPTIONS',
  'CONCUSSIONS', 'CONFIDENCE', 'CONFISCATED', 'CONFRONTING', 'CONJUNCTION', 'CONSPIRATOR', 'CONSTRAINING',
  'CONSULTATION', 'CONTAINMENT', 'CONTRADICTS', 'CONTRIBUTIONS', 'CONVENTIONS', 'CONVERSATIONS', 'CORPORATIONS',
  'COUNTRYSIDE', 'CREDENTIALS', 'CRITICIZING', 'CURIOSITIES', 'DANGEROUSNESS', 'DEBILITATED', 'DECORATIONS',
  'DEFICIENCIES', 'DELIBERATED', 'DELIVERANCE', 'DEMONSTRATED', 'DENUNCIATED', 'DEPORTATION', 'DESCRIPTION',
  'DESTINATION', 'DISTORTIONS'
];

/**
 * Gets the word list based on the number of letters
 */
export const getWordList = (numberOfLetters: number): string[] => {
  switch (numberOfLetters) {
    case 4:
      return WORDS_4;
    case 5:
      return WORDS_5;
    case 6:
      return WORDS_6;
    case 7:
      return WORDS_7;
    case 8:
      return WORDS_8;
    case 9:
      return WORDS_9;
    case 10:
      return WORDS_10;
    case 11:
      return WORDS_11;
    default:
      return WORDS_5; // Default to 5-letter words
  }
};

/**
 * Gets a random word from the list based on the number of letters
 */
export const getRandomWord = (numberOfLetters: number): string => {
  const words = getWordList(numberOfLetters);
  return words[Math.floor(Math.random() * words.length)];
};

/**
 * Checks if a word is valid for guessing based on the number of letters
 */
export const isValidWord = (word: string, numberOfLetters: number): boolean => {
  const validGuesses = getWordList(numberOfLetters);
  return validGuesses.includes(word);
};